### ISSUE TITLE
Purpose of downsampling

### ISSUE THREAD

**Issue by d-paliwal** [digitalcytometry/cytospace#100]
Hi! Thank you so much for your tool! I am wondering if you could please clarify what the purpose of downsampling to 1500 transcripts is. Thanks in advance!

**Comment by erinlbrown** [comment]
Hi, thank you for your interest in CytoSPACE! Downsampling transcripts serves as a form of normalization and ensures that the cell-to-spot assignments will be independent of the total transcript count per cell. Hope that helps clarify!

**Comment by erinlbrown** [comment]
While the downsampling component can address batch effects, its inclusion within the method (also) targets biological variation in nonzero gene counts per cell, often related to cell type/state, so that in assessing the match between single cell and spatial profiles, certain cell types are not inherently privileged due to higher or lower sparsity in the scRNA-seq. This is particularly relevant for bulk spatial profiles such as Visium, for which the sparsity of the spatial RNA-seq profile may be more representative of the total number or heterogeneity of cells per spot, rather than the transcriptomic sparsity of individual cells. In general, we have found CytoSPACE to be highly robust to noise and moderate variation in inputs, and no other batch correction is generally recommended. Hope this helps clarify!
