### ISSUE TITLE
cannot open file 'get_cellfracs_seuratv3.R

### ISSUE THREAD

**Issue by gakabani** [digitalcytometry/cytospace#54]
I installed cellspace on a mac running OS 13.2.1.
Then, I tried to run the example given on the website, and I got the following error.

(cytospace) gamalakabani:03/07/23:~$ cytospace -sp brca_scRNA_GEP.txt -ctp brca_scRNA_celllabels.txt -stp brca_STdata_GEP.txt -cp brca_STdata_coordinates.txt -o cytospace_results_brca
Read and validate data ...
100% |██████████████████████████████████████████████████| Reading data [done]
Estimating cell type fractions
Fatal error: cannot open file 'get_cellfracs_seuratv3.R': No such file or directory
Error estimating cell type fractions

If get_cellfracs_seuratv3.R is located in the input directory, it works, but then I get the following error

Error: package or namespace load failed for ‘Seurat’ in library.dynam(lib, package, package.lib):
 shared object ‘rlang.dylib’ not found
Execution halted
Error estimating cell type fractions

I would appreciate any help, as I am writing a manuscript for my course in Bioinformatics on spatial transcriptomics.

Thank you

Gamal

**Comment by hsjeon-k** [comment]
Thank you for letting us know.

CytoSPACE currently needs to be run inside the cloned directory in order to find the R script that you mentioned. Thank you for letting us know about the issue, and we will make this part more clear.

The `shared object 'rlang.dylib' not found` error seems like it may be something related to the environment setup. Could you maybe try re-installing the rlang library in R inside the cytospace conda environment?

Alternatively, you can separately generate the cell type fractional composition file (using the get_cellfracs_seuratv3.R script, or with a different approach of your own), and pass it in as an additional argument with the -ctfep flag. For more information regarding what this file should look like, please see the "Advanced options - User-provided fractional composition of each cell type" section of the README file. When this file is passed in as an argument, CytoSPACE will not run the R script internally. 

Thank you, please let us how this goes!

**Comment by WubingZhang** [comment]
> I installed cellspace on a mac running OS 13.2.1. Then, I tried to run the example given on the website, and I got the following error.
> 
> (cytospace) gamalakabani:03/07/23:~$ cytospace -sp brca_scRNA_GEP.txt -ctp brca_scRNA_celllabels.txt -stp brca_STdata_GEP.txt -cp brca_STdata_coordinates.txt -o cytospace_results_brca Read and validate data ... 100% |██████████████████████████████████████████████████| Reading data [done] Estimating cell type fractions Fatal error: cannot open file 'get_cellfracs_seuratv3.R': No such file or directory Error estimating cell type fractions
> 
> If get_cellfracs_seuratv3.R is located in the input directory, it works, but then I get the following error
> 
> Error: package or namespace load failed for ‘Seurat’ in library.dynam(lib, package, package.lib): shared object ‘rlang.dylib’ not found Execution halted Error estimating cell type fractions
> 
> I would appreciate any help, as I am writing a manuscript for my course in Bioinformatics on spatial transcriptomics.
> 
> Thank you
> 
> Gamal

Hi,

We have resolved the problem related to get_cellfracs_seuratv3.R. Please update cytospace following the "Updating local installations" in the documentation and try again. Please let us know if there is a further problem.

Thanks!
Wubing

**Comment by Hannah-Doerpholz** [comment]
I actually ran into the exact same error as @QianhuiXu . Should I open another issue for this or is there already a solution to the problem?

**Comment by hsjeon-k** [comment]
Hello! Thank you for the comment.
I will follow up on this on the new issue thread (#71). Please feel free to add to the discussion there!
