### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int' in plot.py

### ISSUE THREAD

**Issue by suerle** [digitalcytometry/cytospace#78]
Hi!

When running 

cytospace \
   --scRNA-path sc_ref_output_scRNA_data.txt \
   --cell-type-path cell_labels.txt \
   --spaceranger-path sr_output.tar.gz \
   -sm lap_CSPR

I encounter the following error:

  File "/Users/miniconda3/envs/cytospace/lib/python3.8/site-packages/cytospace/post_processing/plot.py", line 63, in plot_results_bulk_ST_by_spot
    scale = Y.max() < 500 and ((Y - Y.round()).abs() < 1e-5).all()
TypeError: '<' not supported between instances of 'str' and 'int'

Any recommendations on how to fix?

Thanks and best
suerle

**Comment by erinlbrown** [comment]
Hi, this is likely related to your tar.gz Space Ranger input. We have encountered errors with outputs from the newest versions of Space Ranger due to a small change in format. We plan to release a fix for this soon, but in the meanwhile you should be able to circumvent this error by deleting the header row from the “tissue_positions.csv” file from the Space Ranger outputs before preparing the tar.gz. Alternatively, if you prefer, you might convert the spatial data to the default tab-delimited file input formats instead. Hope this helps!

**Comment by suerle** [comment]
Solved, thank you!
