### ISSUE TITLE
scRNA-seq reference

### ISSUE THREAD

**Issue by ChenJin2020** [digitalcytometry/cytospace#81]
Hello,

Thanks for the fascinating tool. I am interested in using a combined reference dataset containing both 10x Genomics-based and SMART-seq2 scRNA-seq data. The available 10x scRNA-seq data only contains sequences from somatic cells, while the SMART-seq2 data only contains sequences from oocytes. Using the 10x data alone as a reference would lack representation of oocyte transcripts. I wanted to check whether you recommend analyzing the somatic cell and oocyte scRNA-seq data separately using the appropriate 10x and SMART-seq2 reference datasets, or combining the 10x and SMART-seq2 reference data into an integrated dataset first.

**Comment by WubingZhang** [comment]
Hi,

It might depend on what analysis you plan to do after running CytoSPACE. Technically, if you believe there should be somatic cells and oocytes in the tissue slide, where the spatial data is from. I would suggest using integrated scRNA-seq data so that all cell types are present and mapped to the spatial data.

**Comment by ChenJin2020** [comment]
Hi Wubing,

Thank you for getting back to me so quickly.
